Improved deployment scripts

diff --git a/deployment/scripts/check_gcloud_config b/deployment/scripts/check_gcloud_config
--- a/deployment/scripts/check_gcloud_config
+++ b/deployment/scripts/check_gcloud_config
@@ -3,32 +3,46 @@ SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
 cd $SCRIPTPATH; cd ../../
 PLATFORM_NAME=$(basename `pwd`)
 ENVIRONMENT=$1
+# Use fallback to switch to requested
+# project if it's safe to do so.
+FALLBACK=$2
 
 if [ "$ENVIRONMENT" == "" ]; then
   echo "Usage: $0 <environment>"
   exit 1
 fi
 
+export $(grep -v '^#' deployment/$ENVIRONMENT/env.conf | xargs)
 
-export $(cat deployment/$ENVIRONMENT/env.conf | xargs)
 CURRENT_GCLOUD_PROJECT=`gcloud config get-value project`
 CURRENT_GCLOUD_COMPUTE_ZONE=`gcloud config get-value compute/zone`
 CURRENT_GCLOUD_KUBERNETES_CLUSTER_NAME=`gcloud config get-value container/cluster`
 
-if [ "$GCLOUD_PROJECT" != "$CURRENT_GCLOUD_PROJECT" ]; then
-  echo "Invalid Google Cloud config (use authorize script): project = $CURRENT_GCLOUD_PROJECT"
-  exit 1
-fi
+check_config () {
+  if [ "$GCLOUD_PROJECT" != "$CURRENT_GCLOUD_PROJECT" ]; then
+    echo "Invalid Google Cloud config (use authorize script): project = $CURRENT_GCLOUD_PROJECT"
+  fi
 
-if [ "$GCLOUD_COMPUTE_ZONE" != "$CURRENT_GCLOUD_COMPUTE_ZONE" ]; then
-  echo "Invalid Google Cloud config (use authorize script): compute/zone = $CURRENT_GCLOUD_COMPUTE_ZONE"
-  exit 1
-fi
+  if [ "$GCLOUD_COMPUTE_ZONE" != "$CURRENT_GCLOUD_COMPUTE_ZONE" ]; then
+    echo "Invalid Google Cloud config (use authorize script): compute/zone = $CURRENT_GCLOUD_COMPUTE_ZONE"
+  fi
 
-if [ "$GCLOUD_KUBERNETES_CLUSTER_NAME" != "$CURRENT_GCLOUD_KUBERNETES_CLUSTER_NAME" ]; then
-  echo "Invalid Google Cloud config (use authorize script): container/cluster = $CURRENT_GCLOUD_KUBERNETES_CLUSTER_NAME"
-  exit 1
-fi
+  if [ "$GCLOUD_KUBERNETES_CLUSTER_NAME" != "$CURRENT_GCLOUD_KUBERNETES_CLUSTER_NAME" ]; then
+    echo "Invalid Google Cloud config (use authorize script): container/cluster = $CURRENT_GCLOUD_KUBERNETES_CLUSTER_NAME"
+  fi
 
-echo "Using Google Cloud environment $ENVIRONMENT (project=$GCLOUD_PROJECT, compute/zone=$GCLOUD_COMPUTE_ZONE, cluster=$GCLOUD_KUBERNETES_CLUSTER_NAME)"
-exit 0
+}
+
+error=$(check_config)
+if [ "$error" != "" ]; then
+  if [ "$FALLBACK" != "" ]; then
+    echo "Switching project to $PLATFORM_NAME-$ENVIRONMENT."
+    ./deployment/scripts/authorize $ENVIRONMENT
+    exit 0
+  else
+    echo $error
+    exit 1
+  fi
+else
+  echo "Using Google Cloud environment $ENVIRONMENT (project=$GCLOUD_PROJECT, compute/zone=$GCLOUD_COMPUTE_ZONE, cluster=$GCLOUD_KUBERNETES_CLUSTER_NAME)"
+fi
